### ISSUE TITLE
CLOSE: Can you help me?

### ISSUE THREAD

**Issue by lehabaev** [inspirehep/magpie#100]
What i do wrong?

```
from magpie import MagpieModel
import os

CURRENT_DIR = os.getcwd()
LABELS = [.. 34 ITEMS ...]

magpie = MagpieModel(
    scaler=os.path.join(CURRENT_DIR, 'temp/scaler'),
    word2vec_model=os.path.join(CURRENT_DIR, 'temp/w2v'),
    labels=LABELS
)
magpie.train('export', LABELS, test_ratio=0.2, nb_epochs=2)
```

```
/Users/alexeybaev/Work/mltnn/env/lib/python3.5/site-packages/Keras-1.2.2-py3.5.egg/keras/engine/topology.py:2146: UserWarning: The `regularizers` attribute of layers/models is deprecated. Regularization losses are now managed via the `losses` layer/model property.
The `regularizers` attribute will be removed after 06/2017.
  warnings.warn('The `regularizers` attribute of layers/models '
Traceback (most recent call last):
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "/Users/alexeybaev/Work/mltnn/app.py", line 20, in <module>
    magpie.train('export', LABELS, test_ratio=0.2, nb_epochs=2)
  File "/Users/alexeybaev/Work/mltnn/env/lib/python3.5/site-packages/magpie-1.0-py3.5.egg/magpie/main.py", line 96, in train
    verbose=verbose,
  File "/Users/alexeybaev/Work/mltnn/env/lib/python3.5/site-packages/Keras-1.2.2-py3.5.egg/keras/models.py", line 672, in fit
    initial_epoch=initial_epoch)
  File "/Users/alexeybaev/Work/mltnn/env/lib/python3.5/site-packages/Keras-1.2.2-py3.5.egg/keras/engine/training.py", line 1116, in fit
    batch_size=batch_size)
  File "/Users/alexeybaev/Work/mltnn/env/lib/python3.5/site-packages/Keras-1.2.2-py3.5.egg/keras/engine/training.py", line 1033, in _standardize_user_data
    exception_prefix='model target')
  File "/Users/alexeybaev/Work/mltnn/env/lib/python3.5/site-packages/Keras-1.2.2-py3.5.egg/keras/engine/training.py", line 124, in standardize_input_data
    str(array.shape))
ValueError: Error when checking model target: expected dense_1 to have shape (None, 34) but got array with shape (2308, 33)
```

**Comment by lehabaev** [comment]
Close, i had duplicates in LABELS.
