### ISSUE TITLE
ValueError: You are trying to load a weight file containing 6 layers into a model with 1 layers.

### ISSUE THREAD

**Issue by yogesh-0586** [inspirehep/magpie#109]
`first.py` file contains following code

from magpie import MagpieModel
magpie = MagpieModel()
magpie.train_word2vec('data/hep-categories', vec_dim=100)
magpie.fit_scaler('data/hep-categories')
labels = ['Gravitation and Cosmology', 'Experiment-HEP', 'Theory-HEP']
magpie.train('data/hep-categories', labels, test_ratio=0.2, nb_epochs=1)
print(magpie.predict_from_text('Stephen Hawking studies black holes'))
magpie.save_word2vec_model('save/my/embeddings/here')
magpie.save_scaler('save/my/scaler/here', overwrite=True)
magpie.save_model('save/my/model/here.h5')

and `second.py` file contains following code

from magpie import MagpieModel
from magpie import utils
from keras.models import load_model

w2v = utils.load_from_disk("save/my/embeddings/here")
scaler = utils.load_from_disk("save/my/scaler/here")
keras_model = load_model("save/my/model/here.h5")
labels = ['Gravitation and Cosmology', 'Experiment-HEP', 'Theory-HEP']
instance = MagpieModel(keras_model=keras_model, word2vec_model=w2v, scaler=scaler, labels=labels)
print(instance.predict_from_text('Stephen Hawking studies black holes'))

but it show following error

> Using TensorFlow backend.
/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py:1242: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  return cls(**config)
Traceback (most recent call last):
  File "/home/yogesh/l7Project/magpie-master/test.py", line 19, in <module>
    keras_model = load_model("save/my/model/here.h5")
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 249, in load_model
    topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2981, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 6 layers into a model with 1 layers.

**Comment by jstypka** [comment]
If you're loading stuff from disk, just pass paths in the `MagpieModel` constructor e.g. 
```python
magpie = MagpieModel(
    keras_model='/save/my/model/here.h5',
    word2vec_model='/save/my/embeddings/here',
    scaler='/save/my/scaler/here',
    labels=['cat', 'dog', 'cow']
)
```

**Comment by yogesh-0586** [comment]
@jstypka I changed code as below 

from magpie import MagpieModel
labels = ['Gravitation and Cosmology', 'Experiment-HEP', 'Theory-HEP']
magpie = MagpieModel(
    keras_model='save/my/model/here.h5',
    word2vec_model='save/my/embeddings/here',
    scaler='save/my/scaler/here',
    labels=labels
)
print(magpie.predict_from_text('Stephen Hawking studies black holes'))

but still got following error

> /usr/bin/python3.5 /home/magpie-master/test.py
Using TensorFlow backend.
/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py:1242: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  return cls(**config)
Traceback (most recent call last):
  File "/home/magpie-master/test.py", line 28, in <module>
    labels=labels
  File "/home/magpie-master/magpie/main.py", line 24, in __init__
    self.load_model(keras_model)
  File "/home/magpie-master/magpie/main.py", line 276, in load_model
    self.keras_model = keras.models.load_model(filepath)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 249, in load_model
    topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2981, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 6 layers into a model with 1 layers.

**Comment by jstypka** [comment]
What's your Keras version in both cases? (Check with `pip list`). It seems like you're saving the model when the Keras version is 1.X.X, while loading in 2.X.X

**Comment by yogesh-0586** [comment]
In my case I used `keras==2.0.5` for both save and load model but it show same issues. I downgrade kreas to `keras==1.2.2` for save and load model then it work fine. It maybe issue in keras version 2.0.5

**Comment by jstypka** [comment]
Yes, `keras==2.X.X` is not supported yet. I have a WIP branch supporting v2.X, but it's not really ready yet. It should work fine for version `1.X.X` though.

**Comment by yogesh-0586** [comment]
@jstypka Thanks for your support I was continue with keras 1.2.2
