### ISSUE TITLE
train_word2vec error

### ISSUE THREAD

**Issue by wuxiongliu1** [inspirehep/magpie#123]
when I call the magpie.train_word2vec,get error message

```
>>> magpie.train_word2vec('/home/wxl/bear/dataset2',vec_dim=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wxl/.local/lib/python3.5/site-packages/magpie/main.py", line 252, in train_word2vec
    self.word2vec_model = train_word2vec(train_dir, vec_dim=vec_dim)
  File "/home/wxl/.local/lib/python3.5/site-packages/magpie/base/word2vec.py", line 120, in train_word2vec
    window=WORD2VEC_CONTEXT,
  File "/home/wxl/.local/lib/python3.5/site-packages/gensim/models/word2vec.py", line 470, in __init__
    self.train(sentences)
  File "/home/wxl/.local/lib/python3.5/site-packages/gensim/models/word2vec.py", line 776, in train
    raise RuntimeError("you must first build vocabulary before training the model")
RuntimeError: you must first build vocabulary before training the model

```
ps:  I already put data file (txt and lab file) in **/home/wxl/bear/dataset2** dir ,

**Comment by jstypka** [comment]
Check this discussion: https://github.com/RaRe-Technologies/gensim/issues/541
