### ISSUE TITLE
Getting ValueError: Error when checking target: expected dense_1 to have shape in Ubuntu 16,Python 2.7  

### ISSUE THREAD

**Issue by rajeshkumargp** [inspirehep/magpie#133]
I have tried to execute the below code in Ubuntu16 64 bit with Python 2.7 in Virtual environment 

Unique Labels  Count 1252 
Input RawData has lot of Text files(.txt) and their equivalent .lab files. 
When I ran the code with lesser number of labels (in 100s), the code ran fine. 

 
```
from magpie import Magpie

magpie = Magpie()
magpie.train_word2vec('InputCustomization/RawData')
magpie.fit_scaler('InputCustomization/RawData')
magpie.init_word_vectors('InputCustomization/RawData')

uniLabels = [] 
with open('InputCustomization/UniqueLabels.txt') as fl: 
     for aLine in fl: 
         aLine = aLine.strip() 
         uniLabels.append(aLine)
        

print len(uniLabels)

magpie.train('InputCustomization/RawData', uniLabels, test_ratio=0.2, epochs=2)
print("Hello PREDICTED OUTPUT will be printed After now  ")
print("********************")
#print(magpie.predict_from_text('Stephen Hawking studies black holes'))
print(magpie.predict_from_file('InputCustomization/RawData/T100075.txt'))

```` 

Error I am getting : 

``` 

$ python hellomagpie.py 
/home/rajeshkumar/TrailGitClones/magpie_git/magpie_py2Dupl/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Fitted to 46611 vectors
Fitted to 7013 vectors
WARNING! Overwriting already trained word2vec model.
WARNING! Overwriting already fitted scaler.
Fitted to 46611 vectors
Fitted to 7013 vectors
1252
WARNING:tensorflow:From /home/rajeshkumar/TrailGitClones/magpie_git/magpie_py2Dupl/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py:497: calling conv1d (from tensorflow.python.ops.nn_ops) with data_format=NHWC is deprecated and will be removed in a future version.
Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead
Traceback (most recent call last):
  File "hellomagpie.py", line 51, in <module>
    magpie.train('InputCustomization/RawData', uniLabels, test_ratio=0.2, epochs=2)
  File "/home/rajeshkumar/TrailGitClones/magpie_git/magpie_py2Dupl/local/lib/python2.7/site-packages/magpie-2.0-py2.7.egg/magpie/main.py", line 107, in train
    verbose=verbose,
  File "/home/rajeshkumar/TrailGitClones/magpie_git/magpie_py2Dupl/local/lib/python2.7/site-packages/keras/engine/training.py", line 1630, in fit
    batch_size=batch_size)
  File "/home/rajeshkumar/TrailGitClones/magpie_git/magpie_py2Dupl/local/lib/python2.7/site-packages/keras/engine/training.py", line 1480, in _standardize_user_data
    exception_prefix='target')
  File "/home/rajeshkumar/TrailGitClones/magpie_git/magpie_py2Dupl/local/lib/python2.7/site-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
**ValueError: Error when checking target: expected dense_1 to have shape (1252,) but got array with shape (1251,)**

``` 

Please guide me so that the issue is resolved.

**Comment by jstypka** [comment]
That's a very peculiar error @rajeshkumargp, in Magpie there's no logic around the number of labels so it should work fine regardless of their number. We managed to train those models on >10000 of labels, so it's definitely possible. You say that it works for couple of hundred labels but not 1252 - is there a threshold number when it stops working? It would be great if you could also enable me to reproduce the error on my machine so I can investigate.

One minor thing, `magpie.init_word_vectors('InputCustomization/RawData')` is equivalent to the two lines above, so you don't need them. It's enough if you run:

```
magpie = Magpie()
magpie.init_word_vectors('InputCustomization/RawData')

print len(uniLabels)
magpie.train('InputCustomization/RawData', uniLabels, test_ratio=0.2, epochs=2)
```

**Comment by rajeshkumargp** [comment]
I rechecked list of unique labels and found that 'ALabel'  and '   ALabel' , although same . This causes error. 
I am closing this issue.
