### ISSUE TITLE
Memory error at input_data level

### ISSUE THREAD

**Issue by ghostviper** [inspirehep/magpie#134]
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 74, in <module>
    train()
  File "train.py", line 58, in train
    magpie.train(corpus, magpie.labels, test_ratio=0.2, epochs=10)
  File "/usr/local/lib/python3.5/dist-packages/magpie-2.0-py3.5.egg/magpie/main.py", line 96, in train
    scaler=self.scaler,
  File "/usr/local/lib/python3.5/dist-packages/magpie-2.0-py3.5.egg/magpie/nn/input_data.py", line 44, in get_data_for_model
    train_data = build_x_and_y(train_files, train_dir, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/magpie-2.0-py3.5.egg/magpie/nn/input_data.py", line 68, in build_x_and_y
    x_matrix = np.zeros((len(filenames), SAMPLE_LENGTH, word2vec_model.vector_size))
MemoryError

**Comment by jstypka** [comment]
You're dataset doesn't fit in memory, use `magpie.batch_train()` instead of `magpie.train()`

**Comment by ghostviper** [comment]
thanks!
