### ISSUE TITLE
Error when running pip install git+https://github.com/inspirehep/magpie.git@v2.0

### ISSUE THREAD

**Issue by jafetmorales** [inspirehep/magpie#155]
This is the output when running <code>pip install git+https://github.com/inspirehep/magpie.git@v2.0</code>
```
Collecting git+https://github.com/inspirehep/magpie.git@v2.0
  Cloning https://github.com/inspirehep/magpie.git (to revision v2.0) to c:\users\jmorales\appdata\local\temp\pip-req-build-idioim4l
Requirement already satisfied: nltk~=3.2 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from magpie==2.0) (3.2.5)
Requirement already satisfied: numpy~=1.12 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from magpie==2.0) (1.15.0)
Collecting scipy~=0.18 (from magpie==2.0)
  Downloading https://files.pythonhosted.org/packages/52/67/d9ef9b5058d4a9e3f0ae641ec151790622cbeb37f157de5773358e2bf3da/scipy-0.19.1.tar.gz (14.1MB)
Collecting gensim~=0.13 (from magpie==2.0)
  Downloading https://files.pythonhosted.org/packages/81/ac/0210f508e3c04aea20c1bd2c9b8d9c3ddd5102984db8000078ccf229bba9/gensim-0.13.4.1-cp35-cp35m-win_amd64.whl (4.7MB)
Requirement already satisfied: scikit-learn~=0.18 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from magpie==2.0) (0.19.1)
Requirement already satisfied: keras~=2.0 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from magpie==2.0) (2.2.0)
Requirement already satisfied: h5py~=2.6 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from magpie==2.0) (2.8.0)
Requirement already satisfied: six in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from nltk~=3.2->magpie==2.0) (1.11.0)
Requirement already satisfied: smart-open>=1.2.1 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from gensim~=0.13->magpie==2.0) (1.6.0)
Requirement already satisfied: pyyaml in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from keras~=2.0->magpie==2.0) (3.12)
Requirement already satisfied: keras-preprocessing==1.0.1 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from keras~=2.0->magpie==2.0) (1.0.1)
Requirement already satisfied: keras-applications==1.0.2 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from keras~=2.0->magpie==2.0) (1.0.2)
Requirement already satisfied: boto3 in c:\users\jmorales\appdata\roaming\python\python35\site-packages (from smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (1.7.66)
Requirement already satisfied: boto>=2.32 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (2.48.0)
Requirement already satisfied: bz2file in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (0.98)
Requirement already satisfied: requests in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (2.19.1)
Requirement already satisfied: botocore<1.11.0,>=1.10.66 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from boto3->smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (1.10.73)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in c:\users\jmorales\appdata\roaming\python\python35\site-packages (from boto3->smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (0.1.13)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\jmorales\appdata\roaming\python\python35\site-packages (from boto3->smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (0.9.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jmorales\appdata\roaming\python\python35\site-packages (from requests->smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (2018.4.16)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from requests->smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from requests->smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from requests->smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (2.7)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from botocore<1.11.0,>=1.10.66->boto3->smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (2.7.3)
Requirement already satisfied: docutils>=0.10 in c:\users\jmorales\appdata\roaming\python\python35\site-packages (from botocore<1.11.0,>=1.10.66->boto3->smart-open>=1.2.1->gensim~=0.13->magpie==2.0) (0.14)
Building wheels for collected packages: magpie, scipy
  Running setup.py bdist_wheel for magpie: started
  Running setup.py bdist_wheel for magpie: finished with status done
  Stored in directory: C:\Users\jmorales\AppData\Local\Temp\pip-ephem-wheel-cache-j2e6p0a5\wheels\73\af\43\c06434b3c17071b262b249ea4c346723e0e772e2adae480f25
  Running setup.py bdist_wheel for scipy: started
  Running setup.py bdist_wheel for scipy: finished with status error
  Complete output from command c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__=C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-uitey289\\scipy\\setup.py;f=getattr(tokenize, open, open)(__file__);code=f.read().replace(\r\n, \n);f.close();exec(compile(code, __file__, exec))" bdist_wheel -d C:\Users\jmorales\AppData\Local\Temp\pip-wheel-o8c060zz --python-tag cp35:
  lapack_opt_info:
  lapack_mkl_info:
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in [c:\\users\\jmorales\\appdata\\local\\programs\\python\\python35\\lib, C:\\, c:\\users\\jmorales\\appdata\\local\\programs\\python\\python35\\libs]
    NOT AVAILABLE

  openblas_lapack_info:
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
  c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:707: UserWarning: Specified path c:\opt\64\lib is invalid.
    return self.get_paths(self.section, key)
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries libopenblas_v0.2.20_mingwpy not found in []
  get_default_fcompiler: matching types: [gnu, intelv, absoft, compaqv, intelev, gnu95, g95, intelvem, intelem, flang]
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Found executable C:\Program Files (x86)\Gow\bin\DF.exe
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  dont know how to compile Fortran code on platform nt
    NOT AVAILABLE

  openblas_clapack_info:
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries libopenblas_v0.2.20_mingwpy not found in []
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
  
    NOT AVAILABLE

  atlas_3_10_info:
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in C:\
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
  
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in C:\
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
  
    NOT AVAILABLE

  atlas_info:
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in C:\
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
  
    NOT AVAILABLE

  c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
  No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack not found in [c:\\users\\jmorales\\appdata\\local\\programs\\python\\python35\\lib, C:\\, c:\\users\\jmorales\\appdata\\local\\programs\\python\\python35\\libs]
    NOT AVAILABLE

  c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  Running from scipy source directory.
  non-existing path in scipy\\integrate: quadpack.h
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\jmorales\AppData\Local\Temp\pip-install-uitey289\scipy\setup.py", line 416, in <module>
      setup_package()
    File "C:\Users\jmorales\AppData\Local\Temp\pip-install-uitey289\scipy\setup.py", line 412, in setup_package
      setup(**metadata)
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\jmorales\AppData\Local\Temp\pip-install-uitey289\scipy\setup.py", line 336, in configuration
      config.add_subpackage(scipy)
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 1024, in add_subpackage
      caller_level = 2)
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 993, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 930, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage(linalg)
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 1024, in add_subpackage
      caller_level = 2)
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 993, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 930, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError(no lapack/blas resources found)
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__=C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-uitey289\\scipy\\setup.py;f=getattr(tokenize, open, open)(__file__);code=f.read().replace(\r\n, \n);f.close();exec(compile(code, __file__, exec))" clean --all:

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesnt touch
                        files that arent checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).


  ----------------------------------------
  Failed cleaning build dir for scipy
Successfully built magpie
Failed to build scipy
scikit-surprise 1.0.6 has requirement scipy>=1.0.0, but youll have scipy 0.19.1 which is incompatible.
Installing collected packages: scipy, gensim, magpie
  Found existing installation: scipy 1.0.0
    Uninstalling scipy-1.0.0:
      Successfully uninstalled scipy-1.0.0
  Running setup.py install for scipy: started
    Running setup.py install for scipy: finished with status error
    Complete output from command c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__=C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-uitey289\\scipy\\setup.py;f=getattr(tokenize, open, open)(__file__);code=f.read().replace(\r\n, \n);f.close();exec(compile(code, __file__, exec))" install --record C:\Users\jmorales\AppData\Local\Temp\pip-record-h5wbrazk\install-record.txt --single-version-externally-managed --compile:

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    lapack_opt_info:
    lapack_mkl_info:
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in [c:\\users\\jmorales\\appdata\\local\\programs\\python\\python35\\lib, C:\\, c:\\users\\jmorales\\appdata\\local\\programs\\python\\python35\\libs]
      NOT AVAILABLE

    openblas_lapack_info:
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
    c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:707: UserWarning: Specified path c:\opt\64\lib is invalid.
      return self.get_paths(self.section, key)
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries libopenblas_v0.2.20_mingwpy not found in []
    get_default_fcompiler: matching types: [gnu, intelv, absoft, compaqv, intelev, gnu95, g95, intelvem, intelem, flang]
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Found executable C:\Program Files (x86)\Gow\bin\DF.exe
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    dont know how to compile Fortran code on platform nt
      NOT AVAILABLE

    openblas_clapack_info:
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries libopenblas_v0.2.20_mingwpy not found in []
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in C:\
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
    
      NOT AVAILABLE

    atlas_3_10_info:
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in C:\
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
    
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in C:\
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
    
      NOT AVAILABLE

    atlas_info:
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\lib
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\users\jmorales\appdata\local\programs\python\python35\libs
    
      NOT AVAILABLE

    c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
    No module named numpy.distutils._msvccompiler in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack not found in [c:\\users\\jmorales\\appdata\\local\\programs\\python\\python35\\lib, C:\\, c:\\users\\jmorales\\appdata\\local\\programs\\python\\python35\\libs]
      NOT AVAILABLE

    c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    non-existing path in scipy\\integrate: quadpack.h
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jmorales\AppData\Local\Temp\pip-install-uitey289\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\jmorales\AppData\Local\Temp\pip-install-uitey289\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\jmorales\AppData\Local\Temp\pip-install-uitey289\scipy\setup.py", line 336, in configuration
        config.add_subpackage(scipy)
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 1024, in add_subpackage
        caller_level = 2)
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 993, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 930, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage(linalg)
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 1024, in add_subpackage
        caller_level = 2)
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 993, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 930, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError(no lapack/blas resources found)
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
  Rolling back uninstall of scipy
Command "c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__=C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-uitey289\\scipy\\setup.py;f=getattr(tokenize, open, open)(__file__);code=f.read().replace(\r\n, \n);f.close();exec(compile(code, __file__, exec))" install --record C:\Users\jmorales\AppData\Local\Temp\pip-record-h5wbrazk\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\jmorales\AppData\Local\Temp\pip-install-uitey289\scipy\
```
This is my setup:
>Python version: 3.5
>OS: Windows 10 Home
>System Type: 64-bit Operating System, x64-based processor
>Processor: AMD A10-8700P Radeon R6

**Comment by jafetmorales** [comment]
Magpie installation fails because scipy installation fails. For Window systems, scipy~=0.18 may need to be installed by hand, since I could not find any Windows wheels for scipy<1.0.0.
