### ISSUE TITLE
model.init_word_vectors fails with file names containing spaces

### ISSUE THREAD

**Issue by rxng** [inspirehep/magpie#85]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "magpie/__init__.py", line 188, in init_word_vectors
    self.train_word2vec(train_dir, vec_dim=vec_dim)
  File "magpie/__init__.py", line 202, in train_word2vec
    self.word2vec_model = train_word2vec(train_dir, vec_dim=vec_dim)
  File "magpie/base/word2vec.py", line 131, in train_word2vec
    window=context,
  File "/Users/rxng/.pyenv/versions/2.7.13/lib/python2.7/site-packages/gensim/models/word2vec.py", line 469, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/Users/rxng/.pyenv/versions/2.7.13/lib/python2.7/site-packages/gensim/models/word2vec.py", line 533, in build_vocab
    self.scan_vocab(sentences, progress_per=progress_per, trim_rule=trim_rule)  # initial survey
  File "/Users/rxng/.pyenv/versions/2.7.13/lib/python2.7/site-packages/gensim/models/word2vec.py", line 545, in scan_vocab
    for sentence_no, sentence in enumerate(sentences):
  File "magpie/base/word2vec.py", line 115, in __iter__
    d = Document(doc_id, os.path.join(self.dirname, fname + '.txt'))
  File "magpie/base/document.py", line 24, in __init__
    raise ValueError("The file " + filepath + " doesn't exist")
ValueError: The file [redacted]/notedown/snippets/python - filter out empty values list.txt doesn't exist

**Comment by jstypka** [comment]
Thanks for the heads up!

We don't do anything with the path in Magpie, just pass it directly to the python file handler. Handling file names, spaces and special signs is not the scope of Magpie, but should be provided by python file handler - I don't think we should do anything in this. Having spaces in the filepaths is usually a bad idea and you probably want to avoid that anyway.
