### ISSUE TITLE
Getting error while importing magpie library!

### ISSUE THREAD

**Issue by sridharmalepati** [inspirehep/magpie#88]
Hi Jan,

Am working on QEmotion. We are getting a error error while importing magpie library! We did not do any changes to the code, which was running fine till now!

Find below the error we got:
```
Traceback (most recent call last):
  File "full_tests.py", line 6, in <module>
    import magpie
  File "/usr/local/lib/python2.7/dist-packages/magpie/__init__.py", line 7, in <module>
    from magpie.base.document import Document
  File "/usr/local/lib/python2.7/dist-packages/magpie/base/document.py", line 8, in <module>
    nltk.download('punkt', quiet=True)  # make sure it's downloaded before using
  File "/usr/local/lib/python2.7/dist-packages/nltk/downloader.py", line 664, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/usr/local/lib/python2.7/dist-packages/nltk/downloader.py", line 534, in incr_download
    try: info = self._info_or_id(info_or_id)
  File "/usr/local/lib/python2.7/dist-packages/nltk/downloader.py", line 508, in _info_or_id
    return self.info(info_or_id)
  File "/usr/local/lib/python2.7/dist-packages/nltk/downloader.py", line 875, in info
    self._update_index()
  File "/usr/local/lib/python2.7/dist-packages/nltk/downloader.py", line 825, in _update_index
    ElementTree.parse(compat.urlopen(self._url)).getroot())
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 23, column 143
```

Thanks in advance for your time..

Regards
Sridhar

**Comment by jstypka** [comment]
Hey, it doesn't look like a Magpie error - it fails when NLTK tries to download its parser.

I made some changes to Magpie recently. Did you reinstall it? Which NLTK version do you have? (you can see it with running "pip list")

**Comment by sridharmalepati** [comment]
Hi Jan,

Thanks for your response....
No we did not do any re-install!

I checked the "pip list" and see the following : nltk (3.2.1)

but when i tried to rerun it reran without any issues.!

thanks for your time!!
Regards
Sridhar

**Comment by jstypka** [comment]
Cool, I'll close it then!
